#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "Running pre-commit checks..."
echo "Running linter (make go.lint)..."
make go.lint
echo "Pre-commit checks passed."
